POST https://node-postgres-utfd.onrender.com/videos
Content-type: application/json

{
    
    "title" : "video node",
    "description" : "te3232ste",
    "duration" : 120

}


###

GET https://node-postgres-utfd.onrender.com/videos

###
PUT http://localhost:3333/videos/7e9acd63-fe6a-41fc-a7b4-122e043795ed
Content-Type: application/json

{
    "title": "video editado",
    "description": "teste editado",
    "duration": 140
}


###
DELETE  http://localhost:3333/videos/7e9acd63-fe6a-41fc-a7b4-122e043795ed